[package]
name = "keyport"
version = "0.2.0"
edition = "2024"
description = "Utility which simplifies working with openssh cli tools"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ruarq/keyport.git"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
